### ISSUE TITLE
Add a button on the top to "add a pattern" 

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/green-software-patterns#105]
Pointing to https://patterns.greensoftware.foundation/guide/#how-to-propose-a-new-pattern-or-a-change-to-a-pattern

**Comment by holanita** [comment]
@jawache I wasn't involved in the discussion so not sure on which page this would be added? do you have an ETA for this?

**Comment by holanita** [comment]
Looks like this has been added to Osama's board already. See [here](https://github.com/Green-Software-Foundation/ops-content/issues/8).

**Comment by holanita** [comment]
Still TBD whether this can be done for COP. Progress can be tracked in the ticket referenced above.

**Comment by holanita** [comment]
Fixed and closed
