### ISSUE TITLE
[PM] Pattern ideas edited by the technical writer

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/green-software-patterns#119]
I'm opening this new issue as this task has been pending for a long time and I can't see any comments in recent meeting agendas. [These](https://github.com/Green-Software-Foundation/green-software-patterns/issues?q=is%3Aopen+is%3Aissue+author%3Aholanita+label%3A%22Proposed+Pattern%22) are the ideas that were originally added by Asim to the GH discussions (I have created issues for each and labeled them as 'proposed pattern'). The technical writer edited these slightly (I added her version to each issue), but she wasn't able to make major edits or add much text. This could be a problem from a copyright perspective. No one has picked them up yet, so this might be worth a discussion.

**Comment by holanita** [comment]
Discussed in today's call. Anyone is welcome to pick up any of these and turn them into PRs.

**Comment by dubrie** [comment]
All patterns referenced here have been converted into PRs and are actively being reviewed
