### ISSUE TITLE
Include pictures in patterns

### ISSUE THREAD

**Issue by markus-ntt-seidl** [Green-Software-Foundation/green-software-patterns#123]
**Is your feature request related to a problem? Please describe.**
When writing about request structures or dynamics (in web) and also for cloud (architecture diagrams?) it would be best to have some sequence diagrams for easier understanding.

**Comment by holanita** [comment]
As discussed in today's call, you are free to add images. Just remember to reference the source.
We can ask our designer to re-design them to match the GSF brand guidelines.
Also, we can ask her to create new images / diagrams if you have specific instructions for her.

**Comment by dubrie** [comment]
Here is an example pattern that uses an image in its body. Note that the URL path for the image is slightly different than the path in the markdown: https://patterns.greensoftware.foundation/catalog/cloud/time-shift-kubernetes-cron-jobs

**Comment by dubrie** [comment]
Closing this issue as there is a resolution and example for images to be included in patterns.
