### ISSUE TITLE
Use sentence case in pattern titles

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/green-software-patterns#133]
As pointed out by @catherinemaughan we should be using sentence case for all the issue titles. 
Currently, some use title case while some use sentence case. 

@catherinemaughan can you fix these inconsistencies in the published patterns now that you started reviewing them?
@dubrie pls incorporate this into the review process and the guide so we avoid this moving forward

**Comment by dubrie** [comment]
Fixed! Will also make changes to any active pull requests with this issue so we don't unintentionally introduce more differences.
