### ISSUE TITLE
Display the SCI equation consistently in patterns

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/green-software-patterns#134]
As pointed out by @catherinemaughan we should use the same formatting for the SCI equation in all patterns. 
Currently, in some patterns it is displayed as simple text and in some the elements of the equation are formatted.

@catherinemaughan can you fix these inconsistencies in the published patterns? let's use the version you suggested
@dubrie pls incorporate this into the review process and the guide so we avoid this moving forward

**Comment by dubrie** [comment]
Fixed! Will also make updates to all the active pull requests so that we don't introduce any new issues
