### ISSUE TITLE
Finalize edits before COP

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/green-software-patterns#168]
@dubrie this is a summary on final edits and todos before COP

- [x] Please review this [pull request](https://github.com/Green-Software-Foundation/green-software-patterns/pull/167) that includes all the suggested changes related to grammar and formatting.
- [x] Review [this document](https://docs.google.com/document/d/1YdM7omg_KcUucgTt3UgQNEHHI7IJXhUSISlIctACGpQ/edit?usp=sharing) as well. This contains some additional edits to tweak some titles. This could help make titles a bit more concise and standardised but we are unsure if these would change the meaning.
- [x] if you agree with changing the titles, can you process these edits on your end as we don't have a PR for these.

**Comment by dubrie** [comment]
Done!  Updates have been merged into main, thank you!!
