### ISSUE TITLE
[PATT] [PM] Weekly stats on website traffic on patterns pages

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/green-software-patterns#192]
@osamajandali Hi. Not sure if you are the right person to contact. This request comes from the Patterns project team. We would like to get weekly reports on website statistics so we have a better understanding on how much traffic this page gets. 

If this works, I'll open another ticket for the Training project as well, since this would be useful for that project as well.

Can you help us with this?

**Comment by osamajandali** [comment]
I can setup google analytics yes
@jawache will that be okay or we can do another thing?

**Comment by zanete** [comment]
@osamajandali google analytics is a go (from @jawache )

**Comment by osamajandali** [comment]
@jawache It turns out that we are using the same tracking id that we use in the website everywhere, in all docusaurus projects, so that means that the traffic we see is coming from all those websites.
Do you think we should keep it like this or we should separate ?

@holanita We have data on google analytics, I am not so good at extracting data but if you tell me what data exactly that you're looking for I can try my best to extract those

**Comment by jawache** [comment]
@osamajandali no we should use a separate Google tracking id, do you know/have permissions how to create them? (You can create like 50 for the same account)

**Comment by osamajandali** [comment]
Now we have tracking separately for Pattern as well as Training websites

**Comment by jawache** [comment]
@osamajandali to confirm can you create the ids yourself? Are you missing perms/access or anything?

**Comment by zanete** [comment]
@jawache yes, @osamajandali has access and he created separate IDs for each of the websites (training and patterns for now).

**Comment by holanita** [comment]
@zanete can you help me figure out where do we find this data in the end?

**Comment by zanete** [comment]
@holanita it sounds like it should be visible here: https://analytics.google.com/ but you would have to be added to the GSF account to view the analytics. I'm not, so I can't check, but you might already be there. If not, @jawache is the one who can help (i believe).

**Comment by holanita** [comment]
@zanete I'm not either. Is there any way we could get this exported so we don't have to look at the analytics each time for each project? The ultimate goal of this ticket was to make this available to the project team, so hope it's ok if I reopen this.

**Comment by jawache** [comment]
@holanita and @zanete i've added you both with full admin access.

I think the best solution would be to get google to send us a weekly emailed report for each website we own (patterns.greensoftware.foundation is different from greensoftware.foundation) to a shared email address.

I'm not sure how to make that happen, it might be a feature of the platform or we might have to pay for a 3rd party service.

**Comment by holanita** [comment]
Okay, I see now. Is there any chance we could build an automated process for that data to be added to a shared spreadsheet instead so we can track changes more easily? Emails are difficult to work with and difficult to share on Github.

**Comment by holanita** [comment]
nice idea, although not a nice role for a 'human'...

**Comment by holanita** [comment]
I like the idea of having admin support though.

**Comment by zanete** [comment]
@holanita can we consider this task closed since the views are being tracked? Or should we leave open until the full process of delivering these metrics in some format to the team is figured out? In that case I would like to remove from web board and from Osama as assignee as he's unlikely to be involved in that.

**Comment by holanita** [comment]
@zanete please open a new ticket for the new task. if someone asks for specific insights, I can share it with them now that I have access to google analytics.
