### ISSUE TITLE
2022 08 09 - Green Software Patterns Agenda

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/green-software-patterns#20]
## Date
2022 08 09 - 1.30pm UTC - See the time in your timezone https://everytimezone.com/s/a8399b00

## Agenda
- [x] Review recently submitted patterns, if any
- [ ] Work on finalizing sample patterns
- [X] Tracking agendas and attendance in Github

## Decisions Made
The team will work on (sample) patterns asynchronously from now on as much as possible
9 sample patterns are now good to go, these will not be subject to consistency review yet (low complexity, samples)

## Action Items completed shortly after the meeting
- [x] #25

## Action Items to be tracked in future agendas
- [ ] Sarah to update the naming in the template (actions - resource) 
- [ ] Sarah/Bill to update the  workflow and contributors guide [on the website](https://patterns.greensoftware.foundation/)

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

### Attendees
**Complete list of attendees: Asim H., Sarah H., Siu C., Tammy M. + Anita H.**

**Comment by ccasher** [comment]
Attended

**Comment by jawache** [comment]
Attended

**Comment by holanita** [comment]
Attended

**Comment by greenhsu123** [comment]
Attended.

**Comment by holanita** [comment]
Closed. Pending items have been added to the current meeting agenda & memo.
