### ISSUE TITLE
[PATTERNS] Audit project repos 

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/green-software-patterns#212]
@osamajandali we have been reviewing all the project repos and found two that seem to be linked to the patterns project, but we can't really tell why. Do you happen to know what these repos were created for? 

[green-software-patterns-nb-web](https://github.com/Green-Software-Foundation/green-software-patterns-nb-web)
[green-software-patterns-dev](https://github.com/Green-Software-Foundation/green-software-patterns-dev)

cc @jawache

**Comment by osamajandali** [comment]
@holanita It is because it is a fork from it; people tend to do a repo fork when they need to take an existing project in a different direction and keep a link to the original project.
Personally, I have no idea what they are created for, maybe @jawache knows.

**Comment by holanita** [comment]
@osamajandali we talked about this with @jawache earlier and none of us had any idea about these repos. Do you guys think it's safe to remove these?

**Comment by zanete** [comment]
@holanita yes, these can be archived / removed, nothing critical depends on these (on behalf of @osamajandali and @jawache )

**Comment by holanita** [comment]
@zanete noted. will be discussed with the OC next week as suggested by Asim and Sean yesterday. we have another summary ticket where this is listed so closing this one
