### ISSUE TITLE
[PM] All patterns should be reviewed by a technical author

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/green-software-patterns#24]
To make sure our quality of writing stays high, I think just like we did for the principles training each pattern should be reviewed by a technical author, either a volunteer from the GSF or a hired staff member. @dubrie / @holanita

**Comment by greenhsu123** [comment]
Currently, we are looking to release approved patterns quarterly. How about we introduce the tech writer phase after consistency review before the release?

**Comment by Cooper-Cole** [comment]
Would be interested to learn more about this and potentially volunteer as the tech writer :)

**Comment by dubrie** [comment]
I think @greenhsu123's suggestion of doing this as part of or right after the consistency review is the right approach. At that point we have vetted the context and alignment so a technical writer can help provide the clarity and consistency of the content that was agreed upon.

**Comment by holanita** [comment]
this has been in progress for a while, latest updates to be discussed in today's call again

**Comment by holanita** [comment]
let me close this. we are adding tasks/issues one by one as needed.
