### ISSUE TITLE
Asim to review why github action to deploy website is broken

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/green-software-patterns#25]

**Comment by jawache** [comment]
This should be fixed now, FYI - every time we have a broken link, i.e. a link in the site which doesn't point anywhere or returns a 404, it fails to build (which is good)

**Comment by dubrie** [comment]
Closing this as the actions are successfully building now: https://github.com/Green-Software-Foundation/green-software-patterns/actions
