### ISSUE TITLE
2022 08 16 - Green Software Patterns Agenda

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/green-software-patterns#27]
## Date
2022-08-16 - 3pm UTC - See the time in your timezone https://everytimezone.com/s/a8399b00

## Agenda
- [x] Discuss the Education WG / sub-working group
- [x] Discussing updates on sample patterns

## Decisions Made
The Education WG will not be launched for now. We'll revisit this right before or after COP. Ideas about future projects and acitvities: workshops, content/knowledge sharing, university level groups like MSLA, student ambassador programs, etc. (Agenda items related to this topic will be added to the Training/Principls Depo)

## Actionable Items
- [ ] (Asim/Osama) Review taxonomy to make it easier to find things (tags, filters, each tag should have an owner/SME)
- [ ] (Asim/Osama) Add SME application form to website
- [ ] (Asim/Anita) Plan the SME recruiting process
- [ ] (Asim/Anita) Create an email template for recruiting SMEs + design
- [ ] (Asim/Anita) Define when and how to do the technical review (before/after consistency review)
- [ ] (Asim/Anita) Get an update on what will be the final project logos and how the pyramid should look like
- [ ] (Bill) to integrate the template with the guide
- [ ] (Bill) Define the right level for a pattern and add to the guide (an example could be: region shifting, time shifting)
- [x] **Added after the meeting:** (Asim) ask experts/SMEs/team to submit pattern ideas via discussions
- [x] **Added after the meeting:** (Anita) editor to review and rewrite sample patterns + create a guide to ensure consistency

## Pending Items from previous meetings
- [ ] (Sarah) to update the naming in the template (actions - resource)
- [ ] (Sarah/Bill) to update the workflow and contributors guide [on the website](https://patterns.greensoftware.foundation/)

## Future plans
- [ ] **As also discussed in the Community WG call on Aug 17,** Asim suggested we should have monthly working sessions where the team can work on patterns simultaneously and discuss details as needed.

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

### Attendees
**Bill J., Sarah H., Akshit B., Cameron C., Markus S., Tammy M. + Anita H.**

**Comment by ccasher** [comment]
Attended

**Comment by jawache** [comment]
Attended

**Comment by dubrie** [comment]
Attended

**Comment by akshitbatra** [comment]
Attended.

**Comment by holanita** [comment]
attended – action items have been updated to include new items, pending ones from previous weeks and future plans

**Comment by holanita** [comment]
Updated - added 2 action items based on our discussion w/Asim after the meeting + 1 future plan based on the WG call
