### ISSUE TITLE
2022 09 06 - Green Software Patterns Agenda & Minutes #44

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/green-software-patterns#45]
## Date
2022-09-01 - 1.30pm UTC

## Agenda
Tasks have been parked as our priority for the week is the training (principles).
TBD: working with the editor, final structure for patterns, working with SMEs

## Discussions 
n/a

## Actionable Items
- [ ] (Anita/Team) double check whether all sample patterns match the updated [template](https://github.com/Green-Software-Foundation/green-software-patterns/blob/dev/TEMPLATE.md)/[guide](https://patterns.greensoftware.foundation/guide)
- [ ] (Bill) add references section to pattern template / issue template 
- [x] (Bill) re-organize guides on the website ([guide](https://patterns.greensoftware.foundation/guide), [initial review guide](https://patterns.greensoftware.foundation/initial-reviewer-guide), [SME review guide](https://patterns.greensoftware.foundation/sme-review-guide))
- [ ] (Asim) turn his recent discussions into new issues
- [x] (Bill/Sarah) add pyramid/triangle to websites 

## Pending Items from previous meetings
- [ ] (Asim/Osama) Review taxonomy to make it easier to find things ([tags](https://github.com/Green-Software-Foundation/green-software-patterns/blob/main/tags.md), filters, each tag should have an owner/SME)
- [ ] (Asim/Osama) Add [SME application form](https://docs.google.com/forms/d/e/1FAIpQLSdNxIGsD-02GS5oDy53YgswzmIN7PDFUDW6bcDMRHTnAtTNjg/viewform) to website

## Future plans
- We might start planning a Hackathon (to build patterns) during the Principles consistency review period
- **As also discussed in the Community WG call on Aug 17,** Asim suggested we should have monthly working sessions where the team can work on patterns simultaneously and discuss details as needed.

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

### Attendees
**Anita H., Asim H., Bill. J., Markus S., Navveen B., Sarah H., Tammy M.**

**Comment by greenhsu123** [comment]
attended

**Comment by holanita** [comment]
attended

**Comment by dubrie** [comment]
attended
