### ISSUE TITLE
[Web] Does the website avoid tracking user behavior and collecting data unnecessarily

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/green-software-patterns#52]
**Describe the pattern you'd like to propose**
User tracking, user data collection, and targeting in advertisements are responsible for significant energy use in many digital products and services. This is primarily due to the large size of tracking and advertising scripts, the energy required to process and track user behavior, and databases collecting vast amounts of user data. Furthermore, this can present a significant violation of user privacy and tangibly degrade user experience.

**Describe specific emission impact from this pattern**
A clear and concise description of how you see this pattern impacting software emissions.

**References to this pattern**
https://sustainablewebdesign.org/does-the-website-avoid-tracking-user-behaviour-and-collecting-data-unnecessarily/

**Additional context**
Add any other context or screenshots about the proposed pattern here.

**Comment by dubrie** [comment]
Converted this pattern to a pull request: https://github.com/Green-Software-Foundation/green-software-patterns/pull/97
