### ISSUE TITLE
[Web] Ensure text remains visible during webfont load

### ISSUE THREAD

**Issue by dubrie** [Green-Software-Foundation/green-software-patterns#57]
**Describe the pattern you'd like to propose**
Fonts are often large files that take awhile to load. Some browsers hide text until the font loads, causing a [flash of invisible text (FOIT)](https://web.dev/avoid-invisible-text).

**Describe specific emission impact from this pattern**
Reduced energy consumption by reducing download size and increased page performance

**References to this pattern**
https://web.dev/font-display/

**Additional context**
Add any other context or screenshots about the proposed pattern here.

**Comment by markus-ntt-seidl** [comment]
I would argue that this is not a pattern that reduces SCI in any way. Sounds to me more like a quality-of-life thing.
The font will be downloaded anyway. With displaying the text twice (one time without the custom font and one time with the font) it's actually increasing SCI as it's rendered twice.

Or is it about reducing the font size so the font downloads faster?
Or additional patters: Consider if custom fonts are really needed?
Or reduce the amount of fonts needed to display the page?
(Just throwing out ideas, here :) )
