### ISSUE TITLE
[Web] Avoid an excessive DOM size

### ISSUE THREAD

**Issue by dubrie** [Green-Software-Foundation/green-software-patterns#60]
**Describe the pattern you'd like to propose**
A large DOM tree can slow down your page performance in multiple ways:

Network efficiency and load performance

A large DOM tree often includes many nodes that aren't visible when the user first loads the page, which unnecessarily increases data costs for your users and slows down load time.

Runtime performance

As users and scripts interact with your page, the browser must constantly [recompute the position and styling of nodes](https://developers.google.com/web/fundamentals/performance/rendering/reduce-the-scope-and-complexity-of-style-calculations?utm_source=lighthouse&utm_medium=cli). A large DOM tree in combination with complicated style rules can severely slow down rendering.

Memory performance

If your JavaScript uses general query selectors such as document.querySelectorAll('li'), you may be unknowingly storing references to a very large number of nodes, which can overwhelm the memory capabilities of your users' devices.

**Describe specific emission impact from this pattern**
Reduced energy consumption by reducing download size and increased page performance

**References to this pattern**
https://web.dev/dom-size/

**Additional context**
Add any other context or screenshots about the proposed pattern here.

**Comment by markus-ntt-seidl** [comment]
I'll take this over
