### ISSUE TITLE
[Web] Preconnect to required origins

### ISSUE THREAD

**Issue by dubrie** [Green-Software-Foundation/green-software-patterns#63]
**Describe the pattern you'd like to propose**
Consider adding preconnect or dns-prefetch resource hints to establish early connections to important third-party origins.

<link rel="preconnect"> informs the browser that your page intends to establish a connection to another origin, and that you'd like the process to start as soon as possible.

Establishing connections often involves significant time in slow networks, particularly when it comes to secure connections, as it may involve DNS lookups, redirects, and several round trips to the final server that handles the user's request.

Taking care of all this ahead of time can make your application feel much snappier to the user without negatively affecting the use of bandwidth. Most of the time in establishing a connection is spent waiting, rather than exchanging data.

**Describe specific emission impact from this pattern**
Reduced energy consumption by reducing download size and increased page performance

**References to this pattern**
https://web.dev/uses-rel-preconnect/

**Additional context**
Add any other context or screenshots about the proposed pattern here.

**Comment by markus-ntt-seidl** [comment]
My understanding of this is, that you add a hint in HTML that you want to connect to a IP in the future. The browser should prepare itself and maybe already establish a connection. In the end the connection establish would be done before the browser is instructed to connect, hence the pre-connect.

I fail to see how this improves SCI as the preconnect might be done in vain, when the resource is not needed.
(Assuming that establishing a connection needs more SCI as the CPU waiting)

**Comment by dubrie** [comment]
I agree with you @markus-ntt-seidl, this was added in during a bulk ingestion of issues from a website and after re-looking at it now it doesn't have much relevance to the SCI. I'll close this issue but if others disagree feel free to reopen.
