### ISSUE TITLE
[Cloud Engineer] Optimize software and architecture for asynchronous and scheduled jobs

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/green-software-patterns#64]
**Describe the pattern you'd like to propose**
Intent: Use efficient software designs and architectures to minimize the average resources required per unit of work. Implement mechanisms that result in even utilization of components to reduce resources that are idle between tasks and minimize the impact of load spikes.

***
**Describe the pattern you'd like to propose**
This pattern involves using efficient software design and architecture so that less resources are required to perform the same tasks. There are different means you can use to achieve this, including:
Queuing non-urgent processing requests
Flattening utilisation across your pipeline with increased serialisation 
Modifying the capacity of some components so that there are no idling resources waiting for input
Optimising the integration of external services with the use of buffers and rate limiting 
Optimising software using the most efficient available hardware 
Maximising utilisation for batch processing with queue-driven architecture, pipeline management and on-demand workers
Scheduling tasks to avoid simultaneous execution of resource contention and load spikes
Scheduling jobs at times of lowest carbon intensity  

**Describe specific emission impact from this pattern**
Using more efficient software design and architecture results in a more even use of components; less resources are left idle and the impact of load spikes is reduced. 
In terms of the SCI impact, this means both M (embodied carbon) and E (energy) are reduced, leading to a lower overall score.

**References to this pattern**
https://docs.aws.amazon.com/wellarchitected/latest/sustainability-pillar/optimize-software-and-architecture-for-asynchronous-and-scheduled-jobs.html

**Additional context**
Add any other context or screenshots about the proposed pattern here.

**Comment by holanita** [comment]
edited version has been added, issue updated

**Comment by greenhsu123** [comment]
I will pick this up!

**Comment by greenhsu123** [comment]
first PR for this issue- https://github.com/Green-Software-Foundation/green-software-patterns/pull/99
