### ISSUE TITLE
[Cloud Engineer] Optimize geographic placement of workloads for user locations

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/green-software-patterns#65]
**Describe the pattern you'd like to propose**
Intent: Analyze network access patterns to identify where your customers are connecting from geographically. Select Regions and services that reduce the distance that network traffic must travel to decrease the total network resources required to support your workload.

***
**Describe the pattern you'd like to propose**
This pattern involves analysing network access patterns for your users so you can select regions that reduce the distance the network traffic needs to travel to complete your workload. There are different means you can use to achieve this, including:
Caching locally for frequently-used resources
Connection pooling to enable reuse of connection 
Edge caching to reduce the amount of data travelling from your origin server
Distributed data stores that don’t rely on persistent connections and synchronous updates to serve local populations
Using shared dynamic capacity in place of pre-provisioned static network capacity

**Describe specific emission impact from this pattern**
Reducing the distance that the network traffic has to travel reduces the overall network resources required to support your workload both in terms of electricity consumed and in terms of the total equipment being utilised.
In terms of the SCI impact, this means both M (embodied carbon) and E (energy) are reduced, leading to a lower overall score.

**References to this pattern**
https://docs.aws.amazon.com/wellarchitected/latest/sustainability-pillar/optimize-geographic-placement-of-workloads-for-user-locations.html

**Additional context**
Add any other context or screenshots about the proposed pattern here.

**Comment by holanita** [comment]
editor's version added at the bottom

**Comment by markus-ntt-seidl** [comment]
It seems this was already done: https://github.com/Green-Software-Foundation/green-software-patterns/blob/dev/docs/catalog/cloud/choose-region-closest-to-users.md
