### ISSUE TITLE
[Web] Remove Unused CSS

### ISSUE THREAD

**Issue by dubrie** [Green-Software-Foundation/green-software-patterns#69]
**Describe the pattern you'd like to propose**
Each external stylesheet must be downloaded from the network. These extra network trips can significantly increase the time that users must wait before they see any content on their screens.

Unused CSS also slows down a browser's construction of the [render tree](https://developers.google.com/web/fundamentals/performance/critical-rendering-path/render-tree-construction). The render tree is like the DOM tree, except that it also includes the styles for each node. To construct the render tree, a browser must walk the entire DOM tree, and check which CSS rules apply to each node. The more unused CSS there is, the more time that a browser might potentially need to spend calculating the styles for each node.

**Describe specific emission impact from this pattern**
Reduced energy consumption by reducing download size and increased page performance

**References to this pattern**
https://web.dev/unused-css-rules/

**Additional context**
Add any other context or screenshots about the proposed pattern here.

**Comment by markus-ntt-seidl** [comment]
Here we go: Taking this over.
