### ISSUE TITLE
[Web] Minify JavaScript

### ISSUE THREAD

**Issue by dubrie** [Green-Software-Foundation/green-software-patterns#70]
**Describe the pattern you'd like to propose**
Minifying JavaScript files can reduce payload sizes and script parse time. The Opportunities section of your Lighthouse report lists all unminified JavaScript files, along with the potential savings in [kibibytes (KiB)](https://en.wikipedia.org/wiki/Kibibyte) when these files are minified

**Describe specific emission impact from this pattern**
Reduced energy consumption by reducing download size and increased page performance

**References to this pattern**
https://web.dev/unminified-javascript/

**Additional context**
Add any other context or screenshots about the proposed pattern here.

**Comment by markus-ntt-seidl** [comment]
I would propose to close this in favour of #79
