### ISSUE TITLE
[Web] Minify CSS

### ISSUE THREAD

**Issue by dubrie** [Green-Software-Foundation/green-software-patterns#72]
**Describe the pattern you'd like to propose**
Minifying CSS files can improve your page load performance. CSS files are often larger than they need to be. For example:

/* Header background should match brand colors. */
h1 {
  background-color: #000000;
}
h2 {
  background-color: #000000;
}
Can be reduced to:

h1, h2 { background-color: #000000; }
From the perspective of the browser, these 2 code samples are functionally equivalent, but the second example uses less bytes. Minifiers can further improve byte efficiency by removing whitespace:

h1,h2{background-color:#000000;}
Some minifiers employ clever tricks to minimize bytes. For example, the color value #000000 can be further reduced to #000, which is its shorthand equivalent.

**Describe specific emission impact from this pattern**
Reduced energy consumption by reducing download size and increased page performance

**References to this pattern**
https://web.dev/unminified-css/

**Additional context**
Add any other context or screenshots about the proposed pattern here.

**Comment by markus-ntt-seidl** [comment]
As far as I can see this largely overlaps with https://github.com/Green-Software-Foundation/green-software-patterns/pull/79
Whereas the PR is more general (minify all assets).

**Comment by markus-ntt-seidl** [comment]
I would propose to close this in favour of #79

**Comment by navveenb** [comment]
I will create a new pull request as I moved web patterns from #79.
