### ISSUE TITLE
[Web] Defer Offscreen Images

### ISSUE THREAD

**Issue by dubrie** [Green-Software-Foundation/green-software-patterns#73]
**Describe the pattern you'd like to propose**
Lazy loading is the approach of waiting to load resources until they are needed, rather than loading them in advance. This can improve performance by reducing the amount of resources that need to be loaded and parsed on initial page load.

Images that are offscreen during the initial pageload are ideal candidates for this technique. Best of all, [lazysizes](https://github.com/aFarkas/lazysizes) makes this a very simple strategy to implement.

**Describe specific emission impact from this pattern**
Reduced energy consumption by reducing download size and increased page performance

**References to this pattern**
- https://web.dev/codelab-use-lazysizes-to-lazyload-images/
- https://web.dev/offscreen-images/

**Additional context**
Add any other context or screenshots about the proposed pattern here.

**Comment by markus-ntt-seidl** [comment]
Taking this over
