### ISSUE TITLE
[Web] Properly Size Images

### ISSUE THREAD

**Issue by dubrie** [Green-Software-Foundation/green-software-patterns#75]
**Describe the pattern you'd like to propose**
Ideally, your page should never serve images that are larger than the version that's rendered on the user's screen. Anything larger than that just results in wasted bytes and slows down page load time.

The main strategy for serving appropriately sized images is called "responsive images". With responsive images, you generate multiple versions of each image, and then specify which version to use in your HTML or CSS using media queries, viewport dimensions, and so on. See [Serve responsive images](https://web.dev/serve-responsive-images) to learn more.

[Image CDNs](https://web.dev/image-cdns/) are another main strategy for serving appropriately sized images. You can think of image CDNs like web service APIs for transforming images.

Another strategy is to use vector-based image formats, like SVG. With a finite amount of code, an SVG image can scale to any size. See [Replace complex icons with SVG](https://web.dev/responsive-images/#replace-complex-icons-with-svg) to learn more.

Tools like [gulp-responsive](https://www.npmjs.com/package/gulp-responsive) or [responsive-images-generator](https://www.npmjs.com/package/responsive-images-generator) can help automate the process of converting an image into multiple formats. There are also image CDNs which let you generate multiple versions, either when you upload an image, or request it from your page.

**Describe specific emission impact from this pattern**
Reduced energy consumption by reducing download size and increased page performance

**References to this pattern**
https://web.dev/uses-responsive-images/

**Additional context**
Add any other context or screenshots about the proposed pattern here.

**Comment by markus-ntt-seidl** [comment]
I'll convert this

**Comment by dubrie** [comment]
Pattern merged
