### ISSUE TITLE
reza_test_pattern

### ISSUE THREAD

**Issue by banirazi** [Green-Software-Foundation/green-software-patterns#77]
**Pattern Description**
This is a test pattern created by Reza Razi, showing that he is familiar with the process.

**Emission Impact**
Reza will contribute as a Subject Matter Expert and will be assigned pull requests in this GitHub repo to review for the following areas of expertise:

- **Technical Domain:** Artificial Intelligence, Machine Learning, Optimization, Control, Robotics 
- **Industry Domain:** Power Generation, Power Distribution, Power Utility, Power Grid, Oil and Gas, Renewable Energy 

**References**
This pattern was created in response to the email Reza received from Bill Johnson.

**Additional Context**
Reza is expected to provide help in each of his expertise areas to:

1. Review submitted patterns to determine if the pattern already exists or is covered by an existing pattern
2. Ensure there is an appropriate level of detail for someone to implement the pattern in their own system
3. Determine the efficacy and accuracy of a submitted pattern
4. Explore splitting or combining patterns as necessary 
5. Provide clear feedback to the submitter if any of these areas are missing or not up to the defined standards
6. Proactively provide feedback to the working group on ways to improve the process, documentation, and content
7. Identify potential new patterns for your areas of expertise.

**Comment by dubrie** [comment]
Hi @banirazi, thanks for creating this! Do you have an example green software pattern you'd like to contribute for the catalog? There are only a few in place now so a lot of opportunity is there. You can create one as a new issue if you have a rough idea (example: https://github.com/Green-Software-Foundation/green-software-patterns/issues/76) or go ahead and use the provided [Template](https://github.com/Green-Software-Foundation/green-software-patterns/edit/dev/TEMPLATE.md) to make a new pull request if you have a good understanding and concept of the pattern. Let me know if you have any questions, thank you!

**Comment by banirazi** [comment]
> 

Hi @dubrie - Does the pattern have to be about software development tools and processes only or the green application of software is acceptable as well? For example, consider using software in the form of AI to maximize renewable energy consumption in the power grid. Could this be considered as a green software pattern?

**Comment by dubrie** [comment]
The Green Software Patterns are focused on software patterns reviewed and curated by the Green Software Foundation that apply to software practitioners, specifically how they can apply the Green Software Principles. The application of Green Software, like the leveraging AI to maximize renewable energy in a power grid, is not part of the scope covered in this project.

**Comment by banirazi** [comment]
In that case, I'm afraid I do not have any pattern in mind to add here.

**Comment by dubrie** [comment]
No worries, if you see any inspiration in other Pattern examples or come across something that would work feel free to open another Issue or Pull Request.
