### ISSUE TITLE
[PM] Hiring SMEs via Upwork

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/green-software-patterns#81]
@dubrie I suggest we test the Upwork hiring process with just one of the key categories first. How about AI as this is where we have least coverage?

If you can let me know briefly what type of skills/profile we are looking for here, I'm happy to do a quick search on Upwork to see what options we have. Usually hiring via Upwork is super fast so if we find the right person, we'll be able to hire them and proceed quickly.

Note that we might have to take this conversation off GH at some point as I don't think I can share the Upwork profile pages and personal data of potential candidates here.

**Comment by jawache** [comment]
@dubrie will provide a paragraph or two by Thursday.

**Comment by dubrie** [comment]
How about this for the recruiting pitch:

> The Green Software Foundation is building a trusted ecosystem of people, standards, tooling, and best practices for green software. As part of this effort, we are creating an open-source database of software patterns that, if applied, will reduce software emissions. Each pattern will be thoroughly reviewed by experts and agreed upon by all members of the Foundation. The patterns are the next step in the Foundation's goal to create an ecosystem of people with the knowledge of how to build greener applications.
> 
> We are looking for a technical content writer to take select previously information from across the internet and produce new green software patterns proposals based on a provided template. This work will help build up our catalog of available patterns for software engineers to use in their designs and systems. 

I haven't used Upwork before but based on some quick searches of existing posts this should be good. Please suggest any updates or thoughts you have!

**Comment by holanita** [comment]
Is this for all 3 areas (AI, web, cloud) or just for some of them? I think we should specify the exact areas and the skills we are looking for so it's easier for people to see whether they are a good fit and also for us to search for matching profiles.

**Comment by jawache** [comment]
Yes agreed, Upwork can be a bit hit and miss but listing exact skills would be a good step.

I think perhaps we focus on people with the technical skills since from experience finding someone with both the tech and writing skills is very hard on upwork.

So Machine Learning Engineer with a focus on performance?

**Comment by jawache** [comment]
In meeting @dubrie 

For Web, take the existing patterns from the internet and turn it into our patterns.

For Cloud, take the existing patterns from the internet and turn it into our patterns.

AI/ML is going to be challenging to find someone on Upwork so we'll leave this.

**Comment by holanita** [comment]
Noted. Draft job posting added to Upwork. Asked Steph to review. We will publish them soon.

**Comment by jawache** [comment]
Can you share the draft with me? (Or is it draft on Upwork so I can see it there?)

**Comment by holanita** [comment]
It's all on Upwork. We have 4 candidates for web atm.

**Comment by jawache** [comment]
Cheers will check them out

**Comment by jawache** [comment]
@holanita to clarify, I'm not needed to pick/approve people, totally happy for you and @dubrie to select ☺️

**Comment by holanita** [comment]
@jawache I can't select as I don't have the knowledge. Can we invite Bill to Upwork so he can discuss the details with the candidates?

**Comment by jawache** [comment]
Ahh sorry, yes let's revisit post COP

**Comment by holanita** [comment]
Remains on hold. As discussed, will be focusing on working with category leads / SMEs for the time being.
