### ISSUE TITLE
Take advantage of datacenters free cooling

### ISSUE THREAD

**Issue by Jan-Kuske** [Green-Software-Foundation/green-software-patterns#84]
**Describe the pattern you'd like to propose**
Shift execution time of batch data pipelines and machine learning models training pipelines to time between late evening to early morning to take advantage of datacenters free cooling.

**Describe specific emission impact from this pattern**
Typical data centers have two operation modes for cooling – regular one where compressors are assisting in pumping heat outside data center and free cooling where external air is used directly to transfer heat from heat exchangers. The second one is much more energy efficient, since compressors are the largest energy consumers in cooling systems but could work only when external temperature is low enough. In practice it means that for most of the year free cooling could be used mainly late evening, at night and early morning. Taking into account that in compressor assistant cooling mode, energy usage for cooling could be comparable to energy used by IT equipment, by simply moving batch workloads to time when free cooling is most likely to be used by data center, we could easily achieve two-digit percentage energy usage reduction. When we combine this gain with usually lower carbon intensity in energy production during off peak hours it will lead to significant carbon emission reduction.

SCI Impact
SCI = ((E * I) + M) per R
Lowers E by lowering cooling overhead 
Lowers I by using energy when carbon mix is more favorable

**References to this pattern**
Currently no published pattern relates to this proposal.

**Additional context**
More info about free cooling [How Data Center Free Cooling Works and Why it is Brilliant (masterdc.com)](https://www.masterdc.com/blog/what-is-data-center-free-cooling-how-does-it-work/)

**Comment by Jan-Kuske** [comment]
H Bill, I'm not sure about low-cost data centers, but for enterprise ones like ones run by Google, Microsoft or Equinix it is very common feature since is rather easy to implement in data centers with central colling system (it is most common design in modern data centers due to better cooling efficacy and reliability). Since it is weather depended, you can't know 100% that free cooling will be used given day/night but even if not, then due to lower delta of temperature between interior and exterior it still will be more efficient. It is similar situation like with carbon intensity of energy in regions using renewables - on a given day situation might be different than general pattern due to weather conditions.

**Comment by dubrie** [comment]
That makes sense, Jan, thanks! It seems like there is not a data feed that software applications can take advantage of like they can with carbon intensity values via WattTime or ElectricityMaps. Without that signal, I'm not sure how this can be connected to software. This would be a great pattern or practice for data center ops teams to adopt though, it seems like it would have a significant impact there!

I'm closing this issue for now, but please feel free to re-open or leave comments if I'm not understanding the situation clearly or there are APIs or data feeds available for software applications to take advantage of this behavior.
